### ISSUE TITLE
android gradle配置有问题

### ISSUE THREAD

**Issue by wzxgww** [cikichen/flutter_geetest_plugin#2]
Android build.gradle文件配置有问题，注释第一行package andoird即可正常运行
------------------------
//package android

group 'me.ithome.geetestplugin'
version '1.0-SNAPSHOT'
...
------
感谢作者分享，除了没有成功的动画意外，配好pod 和 gradle之后还是挺好用的

**Comment by cikichen** [comment]
修复了
